sudo: required
language: java
services:
- docker
install:
- echo "install nothing!"
script:
- echo "no tests!"
after_success:
- docker --version
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- eval $(aws ecr get-login --region us-west-2)
- docker build -t lead-measure-api .
- docker tag lead-measure-api:latest 637088740845.dkr.ecr.us-west-2.amazonaws.com/lead-measure-api:latest
- docker push 637088740845.dkr.ecr.us-west-2.amazonaws.com/lead-measure-api:latest
- aws ecs update-service --cluster default --region us-west-2 --service lead-measure-api --task-definition $(aws ecs register-task-definition --cli-input-json file://lead-measure-api-blueprint-def.json --region us-west-2 | jq .taskDefinition.taskDefinitionArn | awk -F/ '{print $2}' | awk -F\" '{print $1}') --desired-count 1
env:
  global:
  - secure: vYcMrAIQRxQ+rTg/60kL5yfqwqWzURyGuRaJ4Wx1eclkkjmr2y63TO6dI/urhZBU6WqHeBholZ/ERNnbs6w5V2dqzK/rOmoAgSnV+6g4u6EG41nZh8hNGJ+RGURLkBrT4Gy8Q1mY+ckN/E/qk+6PaUXIr7dDd5msNw+PzdW2KdJUnwkSu8FMXEJ6TU3mFm4FZbsZMB+WxNsZQskXcFZJBf7zOTJzBGKcKyB4fTloP0zaMGcUuVuMfMttJ8j6P5c5LLgi41SwiG3YtxmxJjZ5J3qTKakSg6xhOrPyCHXik/dVmj5Mhl49HCFj4pBqKkLuE790TizeKT87sjPG0+36rMWpxCuNGOmVhqaHvfVNQd3/kvwowxF/qRTqMJnE3Pnvuif+n32aCM7diq9caIh0fzxNlwIQkNGxjOLgYbioxXE/0pnhkVhkxrD3UiMvnyDYWiC8ZjGPF0t9NeCMm7nNraHFKAIC37lLyAyK8a9suWF/khWObvzbepZCvCjpOXkowjh0n4Hr2CNclqLIkAf4FDFUS3wvgY72fzCs4iw0Q9KftFsY5NSRNZbX4Zf8ON5Z8SFz1RlEiZ1sBmsh+LTUuhguOCG+2hmAFHEV1gLCvHl9S4xDS3FfETA6OGygclFBzHnCB81oYB/ZatXdgyMCG5yJ8VtRzXrK1kCfGxUPhVo=
  - secure: SxyFxUGKDnUuInoKgDoEQJyb2+1BGvsAteOhR5XfuIBtSqMF3cU4FrIJwzuJpcSvO8nCYqWHHjQM0c5ra+d9Kce862wOtQlifETDlXKQqMq2oQKWdAxhGGioE+A/IOfxsQxSPxdM3D3886Fik90Y0bZKifYyEnzTSOyYvANiom+9V5pSuX2gcBozXEvaKCGFvuS8uDW4587fE+kpDdSjwqWboDdRXAeLhhOUCe29L6q13xIW2iAPjO54AvO3+gsw1L2U8x8tPEGLtT0vE+chBbW+SZJy3G0nAS7Sc1kljL4ecdJutAgKIP3p50hxT7SAJ09tZ4VzDeTlVC9BJHsYlUymkm+amKB63V2nq65BgUbxw5QoMLBHuKGOd/dajsSGyJx8Iyp5ZB30PIfAP2Z6IfZqJN/u/GOLcKg6K1PBkKz9/wOjd7uSgzPxuQrYy7RJS91J8Y/P5xvke7R7fl9pr/1uSr/QV82XeiWctuYEmbkNkPWYJA8kCcFuqfKMz9xVQIwtBLba/73FjZmZo3fGpo9VGSpHXyVirWAbmgNyQPuTJmDE7xqY/aoijjxsM1uhwFoMl6xLhkV+8L/Xdj7ZSi/kKsjSBOmtuOKsG5mjqjZ2oAGW96k53wyq3DtgVKRYC2xNyp7zdUUE4bdRbz8ABTNFk1QNH3NTOJWjlfXAzGg=
