version: "3"
services:
  lead-measure-api:
    build: .
    ports:
     - "4567:4567"
    depends_on:
     - postgres
  postgres:
    image: postgres:latest
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_PASSWORD
     - POSTGRES_USER
     - POSTGRES_DB
